apiVersion: cert-manager.io/v1
  
kind: Certificate
metadata:
  name: kubernetes.blindrivers.com-tls
spec:
  secretName: kubernetes.blindrivers.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kubernetes.blindrivers.com
  dnsNames:
    - kubernetes.blindrivers.com